Traceback (most recent call last):
  File "/Applications/TextMate.app/Contents/SharedSupport/Bundles/Python.tmbundle/Support/cleanup_whitespace.py", line 44, in <module>
    cleanup_whitespace()
  File "/Applications/TextMate.app/Contents/SharedSupport/Bundles/Python.tmbundle/Support/cleanup_whitespace.py", line 11, in cleanup_whitespace
    lines = sys.stdin.readlines()
IOError: [Errno 9] Bad file descriptor
